// Vendored from eotha-contracts (gen/ts/eotha/rtse/v1/exploration.ts, compiled to ESM). DO NOT EDIT;
// regenerate from the contracts repo when exploration.proto changes.
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: eotha/rtse/v1/exploration.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "eotha.rtse.v1";
/** Relative abundance of a resource on a planet */
export var ResourceAbundance;
(function (ResourceAbundance) {
    ResourceAbundance[ResourceAbundance["RESOURCE_ABUNDANCE_UNSPECIFIED"] = 0] = "RESOURCE_ABUNDANCE_UNSPECIFIED";
    ResourceAbundance[ResourceAbundance["RESOURCE_ABUNDANCE_TRACE"] = 1] = "RESOURCE_ABUNDANCE_TRACE";
    ResourceAbundance[ResourceAbundance["RESOURCE_ABUNDANCE_SPARSE"] = 2] = "RESOURCE_ABUNDANCE_SPARSE";
    ResourceAbundance[ResourceAbundance["RESOURCE_ABUNDANCE_MEAGER"] = 3] = "RESOURCE_ABUNDANCE_MEAGER";
    ResourceAbundance[ResourceAbundance["RESOURCE_ABUNDANCE_PLENTIFUL"] = 4] = "RESOURCE_ABUNDANCE_PLENTIFUL";
    ResourceAbundance[ResourceAbundance["RESOURCE_ABUNDANCE_RICH"] = 5] = "RESOURCE_ABUNDANCE_RICH";
    ResourceAbundance[ResourceAbundance["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(ResourceAbundance || (ResourceAbundance = {}));
export function resourceAbundanceFromJSON(object) {
    switch (object) {
        case 0:
        case "RESOURCE_ABUNDANCE_UNSPECIFIED":
            return ResourceAbundance.RESOURCE_ABUNDANCE_UNSPECIFIED;
        case 1:
        case "RESOURCE_ABUNDANCE_TRACE":
            return ResourceAbundance.RESOURCE_ABUNDANCE_TRACE;
        case 2:
        case "RESOURCE_ABUNDANCE_SPARSE":
            return ResourceAbundance.RESOURCE_ABUNDANCE_SPARSE;
        case 3:
        case "RESOURCE_ABUNDANCE_MEAGER":
            return ResourceAbundance.RESOURCE_ABUNDANCE_MEAGER;
        case 4:
        case "RESOURCE_ABUNDANCE_PLENTIFUL":
            return ResourceAbundance.RESOURCE_ABUNDANCE_PLENTIFUL;
        case 5:
        case "RESOURCE_ABUNDANCE_RICH":
            return ResourceAbundance.RESOURCE_ABUNDANCE_RICH;
        case -1:
        case "UNRECOGNIZED":
        default:
            return ResourceAbundance.UNRECOGNIZED;
    }
}
export function resourceAbundanceToJSON(object) {
    switch (object) {
        case ResourceAbundance.RESOURCE_ABUNDANCE_UNSPECIFIED:
            return "RESOURCE_ABUNDANCE_UNSPECIFIED";
        case ResourceAbundance.RESOURCE_ABUNDANCE_TRACE:
            return "RESOURCE_ABUNDANCE_TRACE";
        case ResourceAbundance.RESOURCE_ABUNDANCE_SPARSE:
            return "RESOURCE_ABUNDANCE_SPARSE";
        case ResourceAbundance.RESOURCE_ABUNDANCE_MEAGER:
            return "RESOURCE_ABUNDANCE_MEAGER";
        case ResourceAbundance.RESOURCE_ABUNDANCE_PLENTIFUL:
            return "RESOURCE_ABUNDANCE_PLENTIFUL";
        case ResourceAbundance.RESOURCE_ABUNDANCE_RICH:
            return "RESOURCE_ABUNDANCE_RICH";
        case ResourceAbundance.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
/** Outcome of a planet scan request */
export var ScanResult;
(function (ScanResult) {
    ScanResult[ScanResult["SCAN_RESULT_UNSPECIFIED"] = 0] = "SCAN_RESULT_UNSPECIFIED";
    ScanResult[ScanResult["SCAN_RESULT_SUCCESS"] = 1] = "SCAN_RESULT_SUCCESS";
    ScanResult[ScanResult["SCAN_RESULT_OUT_OF_RANGE"] = 2] = "SCAN_RESULT_OUT_OF_RANGE";
    ScanResult[ScanResult["SCAN_RESULT_COOLDOWN_ACTIVE"] = 3] = "SCAN_RESULT_COOLDOWN_ACTIVE";
    ScanResult[ScanResult["SCAN_RESULT_INVALID_TOKEN"] = 4] = "SCAN_RESULT_INVALID_TOKEN";
    ScanResult[ScanResult["SCAN_RESULT_SENSOR_TIER_EXCEEDED"] = 5] = "SCAN_RESULT_SENSOR_TIER_EXCEEDED";
    ScanResult[ScanResult["SCAN_RESULT_UNKNOWN_PLANET"] = 6] = "SCAN_RESULT_UNKNOWN_PLANET";
    ScanResult[ScanResult["SCAN_RESULT_ALREADY_CHARTED"] = 7] = "SCAN_RESULT_ALREADY_CHARTED";
    ScanResult[ScanResult["UNRECOGNIZED"] = -1] = "UNRECOGNIZED";
})(ScanResult || (ScanResult = {}));
export function scanResultFromJSON(object) {
    switch (object) {
        case 0:
        case "SCAN_RESULT_UNSPECIFIED":
            return ScanResult.SCAN_RESULT_UNSPECIFIED;
        case 1:
        case "SCAN_RESULT_SUCCESS":
            return ScanResult.SCAN_RESULT_SUCCESS;
        case 2:
        case "SCAN_RESULT_OUT_OF_RANGE":
            return ScanResult.SCAN_RESULT_OUT_OF_RANGE;
        case 3:
        case "SCAN_RESULT_COOLDOWN_ACTIVE":
            return ScanResult.SCAN_RESULT_COOLDOWN_ACTIVE;
        case 4:
        case "SCAN_RESULT_INVALID_TOKEN":
            return ScanResult.SCAN_RESULT_INVALID_TOKEN;
        case 5:
        case "SCAN_RESULT_SENSOR_TIER_EXCEEDED":
            return ScanResult.SCAN_RESULT_SENSOR_TIER_EXCEEDED;
        case 6:
        case "SCAN_RESULT_UNKNOWN_PLANET":
            return ScanResult.SCAN_RESULT_UNKNOWN_PLANET;
        case 7:
        case "SCAN_RESULT_ALREADY_CHARTED":
            return ScanResult.SCAN_RESULT_ALREADY_CHARTED;
        case -1:
        case "UNRECOGNIZED":
        default:
            return ScanResult.UNRECOGNIZED;
    }
}
export function scanResultToJSON(object) {
    switch (object) {
        case ScanResult.SCAN_RESULT_UNSPECIFIED:
            return "SCAN_RESULT_UNSPECIFIED";
        case ScanResult.SCAN_RESULT_SUCCESS:
            return "SCAN_RESULT_SUCCESS";
        case ScanResult.SCAN_RESULT_OUT_OF_RANGE:
            return "SCAN_RESULT_OUT_OF_RANGE";
        case ScanResult.SCAN_RESULT_COOLDOWN_ACTIVE:
            return "SCAN_RESULT_COOLDOWN_ACTIVE";
        case ScanResult.SCAN_RESULT_INVALID_TOKEN:
            return "SCAN_RESULT_INVALID_TOKEN";
        case ScanResult.SCAN_RESULT_SENSOR_TIER_EXCEEDED:
            return "SCAN_RESULT_SENSOR_TIER_EXCEEDED";
        case ScanResult.SCAN_RESULT_UNKNOWN_PLANET:
            return "SCAN_RESULT_UNKNOWN_PLANET";
        case ScanResult.SCAN_RESULT_ALREADY_CHARTED:
            return "SCAN_RESULT_ALREADY_CHARTED";
        case ScanResult.UNRECOGNIZED:
        default:
            return "UNRECOGNIZED";
    }
}
function createBasePlanetaryResource() {
    return { resourceType: "", isVolatileGas: false, abundance: 0, grade: 0, purityPct: 0, harmonicFrequencyHz: 0 };
}
export const PlanetaryResource = {
    encode(message, writer = new BinaryWriter()) {
        if (message.resourceType !== "") {
            writer.uint32(10).string(message.resourceType);
        }
        if (message.isVolatileGas !== false) {
            writer.uint32(16).bool(message.isVolatileGas);
        }
        if (message.abundance !== 0) {
            writer.uint32(24).int32(message.abundance);
        }
        if (message.grade !== 0) {
            writer.uint32(32).uint32(message.grade);
        }
        if (message.purityPct !== 0) {
            writer.uint32(45).float(message.purityPct);
        }
        if (message.harmonicFrequencyHz !== 0) {
            writer.uint32(53).float(message.harmonicFrequencyHz);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const previousRecursionDepth = reader.__tsProtoDecodeDepth ?? 0;
        if (previousRecursionDepth >= 100) {
            throw new globalThis.Error("protobuf decode recursion limit exceeded");
        }
        reader.__tsProtoDecodeDepth = previousRecursionDepth + 1;
        try {
            const end = length === undefined ? reader.len : reader.pos + length;
            const message = createBasePlanetaryResource();
            while (reader.pos < end) {
                const tag = reader.uint32();
                switch (tag >>> 3) {
                    case 1: {
                        if (tag !== 10) {
                            break;
                        }
                        message.resourceType = reader.string();
                        continue;
                    }
                    case 2: {
                        if (tag !== 16) {
                            break;
                        }
                        message.isVolatileGas = reader.bool();
                        continue;
                    }
                    case 3: {
                        if (tag !== 24) {
                            break;
                        }
                        message.abundance = reader.int32();
                        continue;
                    }
                    case 4: {
                        if (tag !== 32) {
                            break;
                        }
                        message.grade = reader.uint32();
                        continue;
                    }
                    case 5: {
                        if (tag !== 45) {
                            break;
                        }
                        message.purityPct = reader.float();
                        continue;
                    }
                    case 6: {
                        if (tag !== 53) {
                            break;
                        }
                        message.harmonicFrequencyHz = reader.float();
                        continue;
                    }
                }
                if ((tag & 7) === 4 || tag === 0) {
                    break;
                }
                reader.skip(tag & 7);
            }
            return message;
        }
        finally {
            reader.__tsProtoDecodeDepth = previousRecursionDepth;
        }
    },
    fromJSON(object) {
        return {
            resourceType: isSet(object.resourceType)
                ? globalThis.String(object.resourceType)
                : isSet(object.resource_type)
                    ? globalThis.String(object.resource_type)
                    : "",
            isVolatileGas: isSet(object.isVolatileGas)
                ? globalThis.Boolean(object.isVolatileGas)
                : isSet(object.is_volatile_gas)
                    ? globalThis.Boolean(object.is_volatile_gas)
                    : false,
            abundance: isSet(object.abundance) ? resourceAbundanceFromJSON(object.abundance) : 0,
            grade: isSet(object.grade) ? globalThis.Number(object.grade) : 0,
            purityPct: isSet(object.purityPct)
                ? globalThis.Number(object.purityPct)
                : isSet(object.purity_pct)
                    ? globalThis.Number(object.purity_pct)
                    : 0,
            harmonicFrequencyHz: isSet(object.harmonicFrequencyHz)
                ? globalThis.Number(object.harmonicFrequencyHz)
                : isSet(object.harmonic_frequency_hz)
                    ? globalThis.Number(object.harmonic_frequency_hz)
                    : 0,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.resourceType !== "") {
            obj.resourceType = message.resourceType;
        }
        if (message.isVolatileGas !== false) {
            obj.isVolatileGas = message.isVolatileGas;
        }
        if (message.abundance !== 0) {
            obj.abundance = resourceAbundanceToJSON(message.abundance);
        }
        if (message.grade !== 0) {
            obj.grade = Math.round(message.grade);
        }
        if (message.purityPct !== 0) {
            obj.purityPct = message.purityPct;
        }
        if (message.harmonicFrequencyHz !== 0) {
            obj.harmonicFrequencyHz = message.harmonicFrequencyHz;
        }
        return obj;
    },
    create(base) {
        return PlanetaryResource.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBasePlanetaryResource();
        message.resourceType = object.resourceType ?? "";
        message.isVolatileGas = object.isVolatileGas ?? false;
        message.abundance = object.abundance ?? 0;
        message.grade = object.grade ?? 0;
        message.purityPct = object.purityPct ?? 0;
        message.harmonicFrequencyHz = object.harmonicFrequencyHz ?? 0;
        return message;
    },
};
function createBasePlanetBasicMetrics() {
    return {
        planetId: "",
        name: "",
        biome: "",
        orbitalRadiusAu: 0,
        radiusKm: 0,
        massEarths: 0,
        surfaceGravityG: 0,
        hasAtmosphere: false,
        res12Anchor: "",
    };
}
export const PlanetBasicMetrics = {
    encode(message, writer = new BinaryWriter()) {
        if (message.planetId !== "") {
            writer.uint32(10).string(message.planetId);
        }
        if (message.name !== "") {
            writer.uint32(18).string(message.name);
        }
        if (message.biome !== "") {
            writer.uint32(26).string(message.biome);
        }
        if (message.orbitalRadiusAu !== 0) {
            writer.uint32(33).double(message.orbitalRadiusAu);
        }
        if (message.radiusKm !== 0) {
            writer.uint32(41).double(message.radiusKm);
        }
        if (message.massEarths !== 0) {
            writer.uint32(49).double(message.massEarths);
        }
        if (message.surfaceGravityG !== 0) {
            writer.uint32(57).double(message.surfaceGravityG);
        }
        if (message.hasAtmosphere !== false) {
            writer.uint32(64).bool(message.hasAtmosphere);
        }
        if (message.res12Anchor !== "") {
            writer.uint32(74).string(message.res12Anchor);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const previousRecursionDepth = reader.__tsProtoDecodeDepth ?? 0;
        if (previousRecursionDepth >= 100) {
            throw new globalThis.Error("protobuf decode recursion limit exceeded");
        }
        reader.__tsProtoDecodeDepth = previousRecursionDepth + 1;
        try {
            const end = length === undefined ? reader.len : reader.pos + length;
            const message = createBasePlanetBasicMetrics();
            while (reader.pos < end) {
                const tag = reader.uint32();
                switch (tag >>> 3) {
                    case 1: {
                        if (tag !== 10) {
                            break;
                        }
                        message.planetId = reader.string();
                        continue;
                    }
                    case 2: {
                        if (tag !== 18) {
                            break;
                        }
                        message.name = reader.string();
                        continue;
                    }
                    case 3: {
                        if (tag !== 26) {
                            break;
                        }
                        message.biome = reader.string();
                        continue;
                    }
                    case 4: {
                        if (tag !== 33) {
                            break;
                        }
                        message.orbitalRadiusAu = reader.double();
                        continue;
                    }
                    case 5: {
                        if (tag !== 41) {
                            break;
                        }
                        message.radiusKm = reader.double();
                        continue;
                    }
                    case 6: {
                        if (tag !== 49) {
                            break;
                        }
                        message.massEarths = reader.double();
                        continue;
                    }
                    case 7: {
                        if (tag !== 57) {
                            break;
                        }
                        message.surfaceGravityG = reader.double();
                        continue;
                    }
                    case 8: {
                        if (tag !== 64) {
                            break;
                        }
                        message.hasAtmosphere = reader.bool();
                        continue;
                    }
                    case 9: {
                        if (tag !== 74) {
                            break;
                        }
                        message.res12Anchor = reader.string();
                        continue;
                    }
                }
                if ((tag & 7) === 4 || tag === 0) {
                    break;
                }
                reader.skip(tag & 7);
            }
            return message;
        }
        finally {
            reader.__tsProtoDecodeDepth = previousRecursionDepth;
        }
    },
    fromJSON(object) {
        return {
            planetId: isSet(object.planetId)
                ? globalThis.String(object.planetId)
                : isSet(object.planet_id)
                    ? globalThis.String(object.planet_id)
                    : "",
            name: isSet(object.name) ? globalThis.String(object.name) : "",
            biome: isSet(object.biome) ? globalThis.String(object.biome) : "",
            orbitalRadiusAu: isSet(object.orbitalRadiusAu)
                ? globalThis.Number(object.orbitalRadiusAu)
                : isSet(object.orbital_radius_au)
                    ? globalThis.Number(object.orbital_radius_au)
                    : 0,
            radiusKm: isSet(object.radiusKm)
                ? globalThis.Number(object.radiusKm)
                : isSet(object.radius_km)
                    ? globalThis.Number(object.radius_km)
                    : 0,
            massEarths: isSet(object.massEarths)
                ? globalThis.Number(object.massEarths)
                : isSet(object.mass_earths)
                    ? globalThis.Number(object.mass_earths)
                    : 0,
            surfaceGravityG: isSet(object.surfaceGravityG)
                ? globalThis.Number(object.surfaceGravityG)
                : isSet(object.surface_gravity_g)
                    ? globalThis.Number(object.surface_gravity_g)
                    : 0,
            hasAtmosphere: isSet(object.hasAtmosphere)
                ? globalThis.Boolean(object.hasAtmosphere)
                : isSet(object.has_atmosphere)
                    ? globalThis.Boolean(object.has_atmosphere)
                    : false,
            res12Anchor: isSet(object.res12Anchor)
                ? globalThis.String(object.res12Anchor)
                : isSet(object.res12_anchor)
                    ? globalThis.String(object.res12_anchor)
                    : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.planetId !== "") {
            obj.planetId = message.planetId;
        }
        if (message.name !== "") {
            obj.name = message.name;
        }
        if (message.biome !== "") {
            obj.biome = message.biome;
        }
        if (message.orbitalRadiusAu !== 0) {
            obj.orbitalRadiusAu = message.orbitalRadiusAu;
        }
        if (message.radiusKm !== 0) {
            obj.radiusKm = message.radiusKm;
        }
        if (message.massEarths !== 0) {
            obj.massEarths = message.massEarths;
        }
        if (message.surfaceGravityG !== 0) {
            obj.surfaceGravityG = message.surfaceGravityG;
        }
        if (message.hasAtmosphere !== false) {
            obj.hasAtmosphere = message.hasAtmosphere;
        }
        if (message.res12Anchor !== "") {
            obj.res12Anchor = message.res12Anchor;
        }
        return obj;
    },
    create(base) {
        return PlanetBasicMetrics.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBasePlanetBasicMetrics();
        message.planetId = object.planetId ?? "";
        message.name = object.name ?? "";
        message.biome = object.biome ?? "";
        message.orbitalRadiusAu = object.orbitalRadiusAu ?? 0;
        message.radiusKm = object.radiusKm ?? 0;
        message.massEarths = object.massEarths ?? 0;
        message.surfaceGravityG = object.surfaceGravityG ?? 0;
        message.hasAtmosphere = object.hasAtmosphere ?? false;
        message.res12Anchor = object.res12Anchor ?? "";
        return message;
    },
};
function createBasePlanetaryMoon() {
    return { moonId: "", name: "", radiusKm: 0, orbitalDistanceKm: 0, biome: "", res12Anchor: "", hasAtmosphere: false };
}
export const PlanetaryMoon = {
    encode(message, writer = new BinaryWriter()) {
        if (message.moonId !== "") {
            writer.uint32(10).string(message.moonId);
        }
        if (message.name !== "") {
            writer.uint32(18).string(message.name);
        }
        if (message.radiusKm !== 0) {
            writer.uint32(25).double(message.radiusKm);
        }
        if (message.orbitalDistanceKm !== 0) {
            writer.uint32(33).double(message.orbitalDistanceKm);
        }
        if (message.biome !== "") {
            writer.uint32(42).string(message.biome);
        }
        if (message.res12Anchor !== "") {
            writer.uint32(50).string(message.res12Anchor);
        }
        if (message.hasAtmosphere !== false) {
            writer.uint32(56).bool(message.hasAtmosphere);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const previousRecursionDepth = reader.__tsProtoDecodeDepth ?? 0;
        if (previousRecursionDepth >= 100) {
            throw new globalThis.Error("protobuf decode recursion limit exceeded");
        }
        reader.__tsProtoDecodeDepth = previousRecursionDepth + 1;
        try {
            const end = length === undefined ? reader.len : reader.pos + length;
            const message = createBasePlanetaryMoon();
            while (reader.pos < end) {
                const tag = reader.uint32();
                switch (tag >>> 3) {
                    case 1: {
                        if (tag !== 10) {
                            break;
                        }
                        message.moonId = reader.string();
                        continue;
                    }
                    case 2: {
                        if (tag !== 18) {
                            break;
                        }
                        message.name = reader.string();
                        continue;
                    }
                    case 3: {
                        if (tag !== 25) {
                            break;
                        }
                        message.radiusKm = reader.double();
                        continue;
                    }
                    case 4: {
                        if (tag !== 33) {
                            break;
                        }
                        message.orbitalDistanceKm = reader.double();
                        continue;
                    }
                    case 5: {
                        if (tag !== 42) {
                            break;
                        }
                        message.biome = reader.string();
                        continue;
                    }
                    case 6: {
                        if (tag !== 50) {
                            break;
                        }
                        message.res12Anchor = reader.string();
                        continue;
                    }
                    case 7: {
                        if (tag !== 56) {
                            break;
                        }
                        message.hasAtmosphere = reader.bool();
                        continue;
                    }
                }
                if ((tag & 7) === 4 || tag === 0) {
                    break;
                }
                reader.skip(tag & 7);
            }
            return message;
        }
        finally {
            reader.__tsProtoDecodeDepth = previousRecursionDepth;
        }
    },
    fromJSON(object) {
        return {
            moonId: isSet(object.moonId)
                ? globalThis.String(object.moonId)
                : isSet(object.moon_id)
                    ? globalThis.String(object.moon_id)
                    : "",
            name: isSet(object.name) ? globalThis.String(object.name) : "",
            radiusKm: isSet(object.radiusKm)
                ? globalThis.Number(object.radiusKm)
                : isSet(object.radius_km)
                    ? globalThis.Number(object.radius_km)
                    : 0,
            orbitalDistanceKm: isSet(object.orbitalDistanceKm)
                ? globalThis.Number(object.orbitalDistanceKm)
                : isSet(object.orbital_distance_km)
                    ? globalThis.Number(object.orbital_distance_km)
                    : 0,
            biome: isSet(object.biome) ? globalThis.String(object.biome) : "",
            res12Anchor: isSet(object.res12Anchor)
                ? globalThis.String(object.res12Anchor)
                : isSet(object.res12_anchor)
                    ? globalThis.String(object.res12_anchor)
                    : "",
            hasAtmosphere: isSet(object.hasAtmosphere)
                ? globalThis.Boolean(object.hasAtmosphere)
                : isSet(object.has_atmosphere)
                    ? globalThis.Boolean(object.has_atmosphere)
                    : false,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.moonId !== "") {
            obj.moonId = message.moonId;
        }
        if (message.name !== "") {
            obj.name = message.name;
        }
        if (message.radiusKm !== 0) {
            obj.radiusKm = message.radiusKm;
        }
        if (message.orbitalDistanceKm !== 0) {
            obj.orbitalDistanceKm = message.orbitalDistanceKm;
        }
        if (message.biome !== "") {
            obj.biome = message.biome;
        }
        if (message.res12Anchor !== "") {
            obj.res12Anchor = message.res12Anchor;
        }
        if (message.hasAtmosphere !== false) {
            obj.hasAtmosphere = message.hasAtmosphere;
        }
        return obj;
    },
    create(base) {
        return PlanetaryMoon.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBasePlanetaryMoon();
        message.moonId = object.moonId ?? "";
        message.name = object.name ?? "";
        message.radiusKm = object.radiusKm ?? 0;
        message.orbitalDistanceKm = object.orbitalDistanceKm ?? 0;
        message.biome = object.biome ?? "";
        message.res12Anchor = object.res12Anchor ?? "";
        message.hasAtmosphere = object.hasAtmosphere ?? false;
        return message;
    },
};
function createBasePlanetarySurvey() {
    return {
        basicMetrics: undefined,
        scanProgressPct: 0,
        metals: [],
        gases: [],
        resources: [],
        isFullyCharted: false,
        moons: [],
    };
}
export const PlanetarySurvey = {
    encode(message, writer = new BinaryWriter()) {
        if (message.basicMetrics !== undefined) {
            PlanetBasicMetrics.encode(message.basicMetrics, writer.uint32(10).fork()).join();
        }
        if (message.scanProgressPct !== 0) {
            writer.uint32(16).uint32(message.scanProgressPct);
        }
        for (const v of message.metals) {
            writer.uint32(26).string(v);
        }
        for (const v of message.gases) {
            writer.uint32(34).string(v);
        }
        for (const v of message.resources) {
            PlanetaryResource.encode(v, writer.uint32(42).fork()).join();
        }
        if (message.isFullyCharted !== false) {
            writer.uint32(48).bool(message.isFullyCharted);
        }
        for (const v of message.moons) {
            PlanetaryMoon.encode(v, writer.uint32(58).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const previousRecursionDepth = reader.__tsProtoDecodeDepth ?? 0;
        if (previousRecursionDepth >= 100) {
            throw new globalThis.Error("protobuf decode recursion limit exceeded");
        }
        reader.__tsProtoDecodeDepth = previousRecursionDepth + 1;
        try {
            const end = length === undefined ? reader.len : reader.pos + length;
            const message = createBasePlanetarySurvey();
            while (reader.pos < end) {
                const tag = reader.uint32();
                switch (tag >>> 3) {
                    case 1: {
                        if (tag !== 10) {
                            break;
                        }
                        message.basicMetrics = PlanetBasicMetrics.decode(reader, reader.uint32());
                        continue;
                    }
                    case 2: {
                        if (tag !== 16) {
                            break;
                        }
                        message.scanProgressPct = reader.uint32();
                        continue;
                    }
                    case 3: {
                        if (tag !== 26) {
                            break;
                        }
                        message.metals.push(reader.string());
                        continue;
                    }
                    case 4: {
                        if (tag !== 34) {
                            break;
                        }
                        message.gases.push(reader.string());
                        continue;
                    }
                    case 5: {
                        if (tag !== 42) {
                            break;
                        }
                        message.resources.push(PlanetaryResource.decode(reader, reader.uint32()));
                        continue;
                    }
                    case 6: {
                        if (tag !== 48) {
                            break;
                        }
                        message.isFullyCharted = reader.bool();
                        continue;
                    }
                    case 7: {
                        if (tag !== 58) {
                            break;
                        }
                        message.moons.push(PlanetaryMoon.decode(reader, reader.uint32()));
                        continue;
                    }
                }
                if ((tag & 7) === 4 || tag === 0) {
                    break;
                }
                reader.skip(tag & 7);
            }
            return message;
        }
        finally {
            reader.__tsProtoDecodeDepth = previousRecursionDepth;
        }
    },
    fromJSON(object) {
        return {
            basicMetrics: isSet(object.basicMetrics)
                ? PlanetBasicMetrics.fromJSON(object.basicMetrics)
                : isSet(object.basic_metrics)
                    ? PlanetBasicMetrics.fromJSON(object.basic_metrics)
                    : undefined,
            scanProgressPct: isSet(object.scanProgressPct)
                ? globalThis.Number(object.scanProgressPct)
                : isSet(object.scan_progress_pct)
                    ? globalThis.Number(object.scan_progress_pct)
                    : 0,
            metals: globalThis.Array.isArray(object?.metals) ? object.metals.map((e) => globalThis.String(e)) : [],
            gases: globalThis.Array.isArray(object?.gases) ? object.gases.map((e) => globalThis.String(e)) : [],
            resources: globalThis.Array.isArray(object?.resources)
                ? object.resources.map((e) => PlanetaryResource.fromJSON(e))
                : [],
            isFullyCharted: isSet(object.isFullyCharted)
                ? globalThis.Boolean(object.isFullyCharted)
                : isSet(object.is_fully_charted)
                    ? globalThis.Boolean(object.is_fully_charted)
                    : false,
            moons: globalThis.Array.isArray(object?.moons) ? object.moons.map((e) => PlanetaryMoon.fromJSON(e)) : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.basicMetrics !== undefined) {
            obj.basicMetrics = PlanetBasicMetrics.toJSON(message.basicMetrics);
        }
        if (message.scanProgressPct !== 0) {
            obj.scanProgressPct = Math.round(message.scanProgressPct);
        }
        if (message.metals?.length) {
            obj.metals = message.metals;
        }
        if (message.gases?.length) {
            obj.gases = message.gases;
        }
        if (message.resources?.length) {
            obj.resources = message.resources.map((e) => PlanetaryResource.toJSON(e));
        }
        if (message.isFullyCharted !== false) {
            obj.isFullyCharted = message.isFullyCharted;
        }
        if (message.moons?.length) {
            obj.moons = message.moons.map((e) => PlanetaryMoon.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return PlanetarySurvey.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBasePlanetarySurvey();
        message.basicMetrics = (object.basicMetrics !== undefined && object.basicMetrics !== null)
            ? PlanetBasicMetrics.fromPartial(object.basicMetrics)
            : undefined;
        message.scanProgressPct = object.scanProgressPct ?? 0;
        message.metals = object.metals?.map((e) => e) || [];
        message.gases = object.gases?.map((e) => e) || [];
        message.resources = object.resources?.map((e) => PlanetaryResource.fromPartial(e)) || [];
        message.isFullyCharted = object.isFullyCharted ?? false;
        message.moons = object.moons?.map((e) => PlanetaryMoon.fromPartial(e)) || [];
        return message;
    },
};
function createBaseScanPlanetRequest() {
    return { pilotId: "", targetPlanetId: "", systemH3: "", sensorTier: 0, currentProgressPct: 0, continuationToken: "" };
}
export const ScanPlanetRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.pilotId !== "") {
            writer.uint32(10).string(message.pilotId);
        }
        if (message.targetPlanetId !== "") {
            writer.uint32(18).string(message.targetPlanetId);
        }
        if (message.systemH3 !== "") {
            writer.uint32(26).string(message.systemH3);
        }
        if (message.sensorTier !== 0) {
            writer.uint32(32).uint32(message.sensorTier);
        }
        if (message.currentProgressPct !== 0) {
            writer.uint32(40).uint32(message.currentProgressPct);
        }
        if (message.continuationToken !== "") {
            writer.uint32(50).string(message.continuationToken);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const previousRecursionDepth = reader.__tsProtoDecodeDepth ?? 0;
        if (previousRecursionDepth >= 100) {
            throw new globalThis.Error("protobuf decode recursion limit exceeded");
        }
        reader.__tsProtoDecodeDepth = previousRecursionDepth + 1;
        try {
            const end = length === undefined ? reader.len : reader.pos + length;
            const message = createBaseScanPlanetRequest();
            while (reader.pos < end) {
                const tag = reader.uint32();
                switch (tag >>> 3) {
                    case 1: {
                        if (tag !== 10) {
                            break;
                        }
                        message.pilotId = reader.string();
                        continue;
                    }
                    case 2: {
                        if (tag !== 18) {
                            break;
                        }
                        message.targetPlanetId = reader.string();
                        continue;
                    }
                    case 3: {
                        if (tag !== 26) {
                            break;
                        }
                        message.systemH3 = reader.string();
                        continue;
                    }
                    case 4: {
                        if (tag !== 32) {
                            break;
                        }
                        message.sensorTier = reader.uint32();
                        continue;
                    }
                    case 5: {
                        if (tag !== 40) {
                            break;
                        }
                        message.currentProgressPct = reader.uint32();
                        continue;
                    }
                    case 6: {
                        if (tag !== 50) {
                            break;
                        }
                        message.continuationToken = reader.string();
                        continue;
                    }
                }
                if ((tag & 7) === 4 || tag === 0) {
                    break;
                }
                reader.skip(tag & 7);
            }
            return message;
        }
        finally {
            reader.__tsProtoDecodeDepth = previousRecursionDepth;
        }
    },
    fromJSON(object) {
        return {
            pilotId: isSet(object.pilotId)
                ? globalThis.String(object.pilotId)
                : isSet(object.pilot_id)
                    ? globalThis.String(object.pilot_id)
                    : "",
            targetPlanetId: isSet(object.targetPlanetId)
                ? globalThis.String(object.targetPlanetId)
                : isSet(object.target_planet_id)
                    ? globalThis.String(object.target_planet_id)
                    : "",
            systemH3: isSet(object.systemH3)
                ? globalThis.String(object.systemH3)
                : isSet(object.system_h3)
                    ? globalThis.String(object.system_h3)
                    : "",
            sensorTier: isSet(object.sensorTier)
                ? globalThis.Number(object.sensorTier)
                : isSet(object.sensor_tier)
                    ? globalThis.Number(object.sensor_tier)
                    : 0,
            currentProgressPct: isSet(object.currentProgressPct)
                ? globalThis.Number(object.currentProgressPct)
                : isSet(object.current_progress_pct)
                    ? globalThis.Number(object.current_progress_pct)
                    : 0,
            continuationToken: isSet(object.continuationToken)
                ? globalThis.String(object.continuationToken)
                : isSet(object.continuation_token)
                    ? globalThis.String(object.continuation_token)
                    : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.pilotId !== "") {
            obj.pilotId = message.pilotId;
        }
        if (message.targetPlanetId !== "") {
            obj.targetPlanetId = message.targetPlanetId;
        }
        if (message.systemH3 !== "") {
            obj.systemH3 = message.systemH3;
        }
        if (message.sensorTier !== 0) {
            obj.sensorTier = Math.round(message.sensorTier);
        }
        if (message.currentProgressPct !== 0) {
            obj.currentProgressPct = Math.round(message.currentProgressPct);
        }
        if (message.continuationToken !== "") {
            obj.continuationToken = message.continuationToken;
        }
        return obj;
    },
    create(base) {
        return ScanPlanetRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseScanPlanetRequest();
        message.pilotId = object.pilotId ?? "";
        message.targetPlanetId = object.targetPlanetId ?? "";
        message.systemH3 = object.systemH3 ?? "";
        message.sensorTier = object.sensorTier ?? 0;
        message.currentProgressPct = object.currentProgressPct ?? 0;
        message.continuationToken = object.continuationToken ?? "";
        return message;
    },
};
function createBaseScanPlanetResponse() {
    return {
        targetPlanetId: "",
        newProgressPct: 0,
        cooldownUntilMs: "0",
        continuationToken: "",
        survey: undefined,
        chartKey: undefined,
        result: 0,
    };
}
export const ScanPlanetResponse = {
    encode(message, writer = new BinaryWriter()) {
        if (message.targetPlanetId !== "") {
            writer.uint32(10).string(message.targetPlanetId);
        }
        if (message.newProgressPct !== 0) {
            writer.uint32(16).uint32(message.newProgressPct);
        }
        if (message.cooldownUntilMs !== "0") {
            writer.uint32(24).uint64(message.cooldownUntilMs);
        }
        if (message.continuationToken !== "") {
            writer.uint32(34).string(message.continuationToken);
        }
        if (message.survey !== undefined) {
            PlanetarySurvey.encode(message.survey, writer.uint32(42).fork()).join();
        }
        if (message.chartKey !== undefined) {
            PlanetChartKey.encode(message.chartKey, writer.uint32(50).fork()).join();
        }
        if (message.result !== 0) {
            writer.uint32(56).int32(message.result);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const previousRecursionDepth = reader.__tsProtoDecodeDepth ?? 0;
        if (previousRecursionDepth >= 100) {
            throw new globalThis.Error("protobuf decode recursion limit exceeded");
        }
        reader.__tsProtoDecodeDepth = previousRecursionDepth + 1;
        try {
            const end = length === undefined ? reader.len : reader.pos + length;
            const message = createBaseScanPlanetResponse();
            while (reader.pos < end) {
                const tag = reader.uint32();
                switch (tag >>> 3) {
                    case 1: {
                        if (tag !== 10) {
                            break;
                        }
                        message.targetPlanetId = reader.string();
                        continue;
                    }
                    case 2: {
                        if (tag !== 16) {
                            break;
                        }
                        message.newProgressPct = reader.uint32();
                        continue;
                    }
                    case 3: {
                        if (tag !== 24) {
                            break;
                        }
                        message.cooldownUntilMs = reader.uint64().toString();
                        continue;
                    }
                    case 4: {
                        if (tag !== 34) {
                            break;
                        }
                        message.continuationToken = reader.string();
                        continue;
                    }
                    case 5: {
                        if (tag !== 42) {
                            break;
                        }
                        message.survey = PlanetarySurvey.decode(reader, reader.uint32());
                        continue;
                    }
                    case 6: {
                        if (tag !== 50) {
                            break;
                        }
                        message.chartKey = PlanetChartKey.decode(reader, reader.uint32());
                        continue;
                    }
                    case 7: {
                        if (tag !== 56) {
                            break;
                        }
                        message.result = reader.int32();
                        continue;
                    }
                }
                if ((tag & 7) === 4 || tag === 0) {
                    break;
                }
                reader.skip(tag & 7);
            }
            return message;
        }
        finally {
            reader.__tsProtoDecodeDepth = previousRecursionDepth;
        }
    },
    fromJSON(object) {
        return {
            targetPlanetId: isSet(object.targetPlanetId)
                ? globalThis.String(object.targetPlanetId)
                : isSet(object.target_planet_id)
                    ? globalThis.String(object.target_planet_id)
                    : "",
            newProgressPct: isSet(object.newProgressPct)
                ? globalThis.Number(object.newProgressPct)
                : isSet(object.new_progress_pct)
                    ? globalThis.Number(object.new_progress_pct)
                    : 0,
            cooldownUntilMs: isSet(object.cooldownUntilMs)
                ? globalThis.String(object.cooldownUntilMs)
                : isSet(object.cooldown_until_ms)
                    ? globalThis.String(object.cooldown_until_ms)
                    : "0",
            continuationToken: isSet(object.continuationToken)
                ? globalThis.String(object.continuationToken)
                : isSet(object.continuation_token)
                    ? globalThis.String(object.continuation_token)
                    : "",
            survey: isSet(object.survey) ? PlanetarySurvey.fromJSON(object.survey) : undefined,
            chartKey: isSet(object.chartKey)
                ? PlanetChartKey.fromJSON(object.chartKey)
                : isSet(object.chart_key)
                    ? PlanetChartKey.fromJSON(object.chart_key)
                    : undefined,
            result: isSet(object.result) ? scanResultFromJSON(object.result) : 0,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.targetPlanetId !== "") {
            obj.targetPlanetId = message.targetPlanetId;
        }
        if (message.newProgressPct !== 0) {
            obj.newProgressPct = Math.round(message.newProgressPct);
        }
        if (message.cooldownUntilMs !== "0") {
            obj.cooldownUntilMs = message.cooldownUntilMs;
        }
        if (message.continuationToken !== "") {
            obj.continuationToken = message.continuationToken;
        }
        if (message.survey !== undefined) {
            obj.survey = PlanetarySurvey.toJSON(message.survey);
        }
        if (message.chartKey !== undefined) {
            obj.chartKey = PlanetChartKey.toJSON(message.chartKey);
        }
        if (message.result !== 0) {
            obj.result = scanResultToJSON(message.result);
        }
        return obj;
    },
    create(base) {
        return ScanPlanetResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseScanPlanetResponse();
        message.targetPlanetId = object.targetPlanetId ?? "";
        message.newProgressPct = object.newProgressPct ?? 0;
        message.cooldownUntilMs = object.cooldownUntilMs ?? "0";
        message.continuationToken = object.continuationToken ?? "";
        message.survey = (object.survey !== undefined && object.survey !== null)
            ? PlanetarySurvey.fromPartial(object.survey)
            : undefined;
        message.chartKey = (object.chartKey !== undefined && object.chartKey !== null)
            ? PlanetChartKey.fromPartial(object.chartKey)
            : undefined;
        message.result = object.result ?? 0;
        return message;
    },
};
function createBasePlanetChartKey() {
    return { planetId: "", pilotId: "", systemH3: "", completedAtMs: "0", signature: Buffer.alloc(0) };
}
export const PlanetChartKey = {
    encode(message, writer = new BinaryWriter()) {
        if (message.planetId !== "") {
            writer.uint32(10).string(message.planetId);
        }
        if (message.pilotId !== "") {
            writer.uint32(18).string(message.pilotId);
        }
        if (message.systemH3 !== "") {
            writer.uint32(26).string(message.systemH3);
        }
        if (message.completedAtMs !== "0") {
            writer.uint32(32).uint64(message.completedAtMs);
        }
        if (message.signature.length !== 0) {
            writer.uint32(42).bytes(message.signature);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const previousRecursionDepth = reader.__tsProtoDecodeDepth ?? 0;
        if (previousRecursionDepth >= 100) {
            throw new globalThis.Error("protobuf decode recursion limit exceeded");
        }
        reader.__tsProtoDecodeDepth = previousRecursionDepth + 1;
        try {
            const end = length === undefined ? reader.len : reader.pos + length;
            const message = createBasePlanetChartKey();
            while (reader.pos < end) {
                const tag = reader.uint32();
                switch (tag >>> 3) {
                    case 1: {
                        if (tag !== 10) {
                            break;
                        }
                        message.planetId = reader.string();
                        continue;
                    }
                    case 2: {
                        if (tag !== 18) {
                            break;
                        }
                        message.pilotId = reader.string();
                        continue;
                    }
                    case 3: {
                        if (tag !== 26) {
                            break;
                        }
                        message.systemH3 = reader.string();
                        continue;
                    }
                    case 4: {
                        if (tag !== 32) {
                            break;
                        }
                        message.completedAtMs = reader.uint64().toString();
                        continue;
                    }
                    case 5: {
                        if (tag !== 42) {
                            break;
                        }
                        message.signature = Buffer.from(reader.bytes());
                        continue;
                    }
                }
                if ((tag & 7) === 4 || tag === 0) {
                    break;
                }
                reader.skip(tag & 7);
            }
            return message;
        }
        finally {
            reader.__tsProtoDecodeDepth = previousRecursionDepth;
        }
    },
    fromJSON(object) {
        return {
            planetId: isSet(object.planetId)
                ? globalThis.String(object.planetId)
                : isSet(object.planet_id)
                    ? globalThis.String(object.planet_id)
                    : "",
            pilotId: isSet(object.pilotId)
                ? globalThis.String(object.pilotId)
                : isSet(object.pilot_id)
                    ? globalThis.String(object.pilot_id)
                    : "",
            systemH3: isSet(object.systemH3)
                ? globalThis.String(object.systemH3)
                : isSet(object.system_h3)
                    ? globalThis.String(object.system_h3)
                    : "",
            completedAtMs: isSet(object.completedAtMs)
                ? globalThis.String(object.completedAtMs)
                : isSet(object.completed_at_ms)
                    ? globalThis.String(object.completed_at_ms)
                    : "0",
            signature: isSet(object.signature) ? Buffer.from(bytesFromBase64(object.signature)) : Buffer.alloc(0),
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.planetId !== "") {
            obj.planetId = message.planetId;
        }
        if (message.pilotId !== "") {
            obj.pilotId = message.pilotId;
        }
        if (message.systemH3 !== "") {
            obj.systemH3 = message.systemH3;
        }
        if (message.completedAtMs !== "0") {
            obj.completedAtMs = message.completedAtMs;
        }
        if (message.signature.length !== 0) {
            obj.signature = base64FromBytes(message.signature);
        }
        return obj;
    },
    create(base) {
        return PlanetChartKey.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBasePlanetChartKey();
        message.planetId = object.planetId ?? "";
        message.pilotId = object.pilotId ?? "";
        message.systemH3 = object.systemH3 ?? "";
        message.completedAtMs = object.completedAtMs ?? "0";
        message.signature = object.signature ?? Buffer.alloc(0);
        return message;
    },
};
function createBaseClaimSystemChartRequest() {
    return { pilotId: "", systemH3: "", planetKeys: [] };
}
export const ClaimSystemChartRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.pilotId !== "") {
            writer.uint32(10).string(message.pilotId);
        }
        if (message.systemH3 !== "") {
            writer.uint32(18).string(message.systemH3);
        }
        for (const v of message.planetKeys) {
            PlanetChartKey.encode(v, writer.uint32(26).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const previousRecursionDepth = reader.__tsProtoDecodeDepth ?? 0;
        if (previousRecursionDepth >= 100) {
            throw new globalThis.Error("protobuf decode recursion limit exceeded");
        }
        reader.__tsProtoDecodeDepth = previousRecursionDepth + 1;
        try {
            const end = length === undefined ? reader.len : reader.pos + length;
            const message = createBaseClaimSystemChartRequest();
            while (reader.pos < end) {
                const tag = reader.uint32();
                switch (tag >>> 3) {
                    case 1: {
                        if (tag !== 10) {
                            break;
                        }
                        message.pilotId = reader.string();
                        continue;
                    }
                    case 2: {
                        if (tag !== 18) {
                            break;
                        }
                        message.systemH3 = reader.string();
                        continue;
                    }
                    case 3: {
                        if (tag !== 26) {
                            break;
                        }
                        message.planetKeys.push(PlanetChartKey.decode(reader, reader.uint32()));
                        continue;
                    }
                }
                if ((tag & 7) === 4 || tag === 0) {
                    break;
                }
                reader.skip(tag & 7);
            }
            return message;
        }
        finally {
            reader.__tsProtoDecodeDepth = previousRecursionDepth;
        }
    },
    fromJSON(object) {
        return {
            pilotId: isSet(object.pilotId)
                ? globalThis.String(object.pilotId)
                : isSet(object.pilot_id)
                    ? globalThis.String(object.pilot_id)
                    : "",
            systemH3: isSet(object.systemH3)
                ? globalThis.String(object.systemH3)
                : isSet(object.system_h3)
                    ? globalThis.String(object.system_h3)
                    : "",
            planetKeys: globalThis.Array.isArray(object?.planetKeys)
                ? object.planetKeys.map((e) => PlanetChartKey.fromJSON(e))
                : globalThis.Array.isArray(object?.planet_keys)
                    ? object.planet_keys.map((e) => PlanetChartKey.fromJSON(e))
                    : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.pilotId !== "") {
            obj.pilotId = message.pilotId;
        }
        if (message.systemH3 !== "") {
            obj.systemH3 = message.systemH3;
        }
        if (message.planetKeys?.length) {
            obj.planetKeys = message.planetKeys.map((e) => PlanetChartKey.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return ClaimSystemChartRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseClaimSystemChartRequest();
        message.pilotId = object.pilotId ?? "";
        message.systemH3 = object.systemH3 ?? "";
        message.planetKeys = object.planetKeys?.map((e) => PlanetChartKey.fromPartial(e)) || [];
        return message;
    },
};
function createBaseSystemChartKey() {
    return { systemH3: "", pilotId: "", totalBodiesCharted: 0, chartedAtMs: "0", signature: Buffer.alloc(0) };
}
export const SystemChartKey = {
    encode(message, writer = new BinaryWriter()) {
        if (message.systemH3 !== "") {
            writer.uint32(10).string(message.systemH3);
        }
        if (message.pilotId !== "") {
            writer.uint32(18).string(message.pilotId);
        }
        if (message.totalBodiesCharted !== 0) {
            writer.uint32(24).uint32(message.totalBodiesCharted);
        }
        if (message.chartedAtMs !== "0") {
            writer.uint32(32).uint64(message.chartedAtMs);
        }
        if (message.signature.length !== 0) {
            writer.uint32(42).bytes(message.signature);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const previousRecursionDepth = reader.__tsProtoDecodeDepth ?? 0;
        if (previousRecursionDepth >= 100) {
            throw new globalThis.Error("protobuf decode recursion limit exceeded");
        }
        reader.__tsProtoDecodeDepth = previousRecursionDepth + 1;
        try {
            const end = length === undefined ? reader.len : reader.pos + length;
            const message = createBaseSystemChartKey();
            while (reader.pos < end) {
                const tag = reader.uint32();
                switch (tag >>> 3) {
                    case 1: {
                        if (tag !== 10) {
                            break;
                        }
                        message.systemH3 = reader.string();
                        continue;
                    }
                    case 2: {
                        if (tag !== 18) {
                            break;
                        }
                        message.pilotId = reader.string();
                        continue;
                    }
                    case 3: {
                        if (tag !== 24) {
                            break;
                        }
                        message.totalBodiesCharted = reader.uint32();
                        continue;
                    }
                    case 4: {
                        if (tag !== 32) {
                            break;
                        }
                        message.chartedAtMs = reader.uint64().toString();
                        continue;
                    }
                    case 5: {
                        if (tag !== 42) {
                            break;
                        }
                        message.signature = Buffer.from(reader.bytes());
                        continue;
                    }
                }
                if ((tag & 7) === 4 || tag === 0) {
                    break;
                }
                reader.skip(tag & 7);
            }
            return message;
        }
        finally {
            reader.__tsProtoDecodeDepth = previousRecursionDepth;
        }
    },
    fromJSON(object) {
        return {
            systemH3: isSet(object.systemH3)
                ? globalThis.String(object.systemH3)
                : isSet(object.system_h3)
                    ? globalThis.String(object.system_h3)
                    : "",
            pilotId: isSet(object.pilotId)
                ? globalThis.String(object.pilotId)
                : isSet(object.pilot_id)
                    ? globalThis.String(object.pilot_id)
                    : "",
            totalBodiesCharted: isSet(object.totalBodiesCharted)
                ? globalThis.Number(object.totalBodiesCharted)
                : isSet(object.total_bodies_charted)
                    ? globalThis.Number(object.total_bodies_charted)
                    : 0,
            chartedAtMs: isSet(object.chartedAtMs)
                ? globalThis.String(object.chartedAtMs)
                : isSet(object.charted_at_ms)
                    ? globalThis.String(object.charted_at_ms)
                    : "0",
            signature: isSet(object.signature) ? Buffer.from(bytesFromBase64(object.signature)) : Buffer.alloc(0),
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.systemH3 !== "") {
            obj.systemH3 = message.systemH3;
        }
        if (message.pilotId !== "") {
            obj.pilotId = message.pilotId;
        }
        if (message.totalBodiesCharted !== 0) {
            obj.totalBodiesCharted = Math.round(message.totalBodiesCharted);
        }
        if (message.chartedAtMs !== "0") {
            obj.chartedAtMs = message.chartedAtMs;
        }
        if (message.signature.length !== 0) {
            obj.signature = base64FromBytes(message.signature);
        }
        return obj;
    },
    create(base) {
        return SystemChartKey.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseSystemChartKey();
        message.systemH3 = object.systemH3 ?? "";
        message.pilotId = object.pilotId ?? "";
        message.totalBodiesCharted = object.totalBodiesCharted ?? 0;
        message.chartedAtMs = object.chartedAtMs ?? "0";
        message.signature = object.signature ?? Buffer.alloc(0);
        return message;
    },
};
function createBaseClaimSystemChartResponse() {
    return { systemH3: "", systemKey: undefined };
}
export const ClaimSystemChartResponse = {
    encode(message, writer = new BinaryWriter()) {
        if (message.systemH3 !== "") {
            writer.uint32(10).string(message.systemH3);
        }
        if (message.systemKey !== undefined) {
            SystemChartKey.encode(message.systemKey, writer.uint32(18).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const previousRecursionDepth = reader.__tsProtoDecodeDepth ?? 0;
        if (previousRecursionDepth >= 100) {
            throw new globalThis.Error("protobuf decode recursion limit exceeded");
        }
        reader.__tsProtoDecodeDepth = previousRecursionDepth + 1;
        try {
            const end = length === undefined ? reader.len : reader.pos + length;
            const message = createBaseClaimSystemChartResponse();
            while (reader.pos < end) {
                const tag = reader.uint32();
                switch (tag >>> 3) {
                    case 1: {
                        if (tag !== 10) {
                            break;
                        }
                        message.systemH3 = reader.string();
                        continue;
                    }
                    case 2: {
                        if (tag !== 18) {
                            break;
                        }
                        message.systemKey = SystemChartKey.decode(reader, reader.uint32());
                        continue;
                    }
                }
                if ((tag & 7) === 4 || tag === 0) {
                    break;
                }
                reader.skip(tag & 7);
            }
            return message;
        }
        finally {
            reader.__tsProtoDecodeDepth = previousRecursionDepth;
        }
    },
    fromJSON(object) {
        return {
            systemH3: isSet(object.systemH3)
                ? globalThis.String(object.systemH3)
                : isSet(object.system_h3)
                    ? globalThis.String(object.system_h3)
                    : "",
            systemKey: isSet(object.systemKey)
                ? SystemChartKey.fromJSON(object.systemKey)
                : isSet(object.system_key)
                    ? SystemChartKey.fromJSON(object.system_key)
                    : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.systemH3 !== "") {
            obj.systemH3 = message.systemH3;
        }
        if (message.systemKey !== undefined) {
            obj.systemKey = SystemChartKey.toJSON(message.systemKey);
        }
        return obj;
    },
    create(base) {
        return ClaimSystemChartResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseClaimSystemChartResponse();
        message.systemH3 = object.systemH3 ?? "";
        message.systemKey = (object.systemKey !== undefined && object.systemKey !== null)
            ? SystemChartKey.fromPartial(object.systemKey)
            : undefined;
        return message;
    },
};
function createBaseQueryChartRequest() {
    return { planetKey: undefined, systemKey: undefined };
}
export const QueryChartRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.planetKey !== undefined) {
            PlanetChartKey.encode(message.planetKey, writer.uint32(34).fork()).join();
        }
        if (message.systemKey !== undefined) {
            SystemChartKey.encode(message.systemKey, writer.uint32(42).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const previousRecursionDepth = reader.__tsProtoDecodeDepth ?? 0;
        if (previousRecursionDepth >= 100) {
            throw new globalThis.Error("protobuf decode recursion limit exceeded");
        }
        reader.__tsProtoDecodeDepth = previousRecursionDepth + 1;
        try {
            const end = length === undefined ? reader.len : reader.pos + length;
            const message = createBaseQueryChartRequest();
            while (reader.pos < end) {
                const tag = reader.uint32();
                switch (tag >>> 3) {
                    case 4: {
                        if (tag !== 34) {
                            break;
                        }
                        message.planetKey = PlanetChartKey.decode(reader, reader.uint32());
                        continue;
                    }
                    case 5: {
                        if (tag !== 42) {
                            break;
                        }
                        message.systemKey = SystemChartKey.decode(reader, reader.uint32());
                        continue;
                    }
                }
                if ((tag & 7) === 4 || tag === 0) {
                    break;
                }
                reader.skip(tag & 7);
            }
            return message;
        }
        finally {
            reader.__tsProtoDecodeDepth = previousRecursionDepth;
        }
    },
    fromJSON(object) {
        return {
            planetKey: isSet(object.planetKey)
                ? PlanetChartKey.fromJSON(object.planetKey)
                : isSet(object.planet_key)
                    ? PlanetChartKey.fromJSON(object.planet_key)
                    : undefined,
            systemKey: isSet(object.systemKey)
                ? SystemChartKey.fromJSON(object.systemKey)
                : isSet(object.system_key)
                    ? SystemChartKey.fromJSON(object.system_key)
                    : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.planetKey !== undefined) {
            obj.planetKey = PlanetChartKey.toJSON(message.planetKey);
        }
        if (message.systemKey !== undefined) {
            obj.systemKey = SystemChartKey.toJSON(message.systemKey);
        }
        return obj;
    },
    create(base) {
        return QueryChartRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseQueryChartRequest();
        message.planetKey = (object.planetKey !== undefined && object.planetKey !== null)
            ? PlanetChartKey.fromPartial(object.planetKey)
            : undefined;
        message.systemKey = (object.systemKey !== undefined && object.systemKey !== null)
            ? SystemChartKey.fromPartial(object.systemKey)
            : undefined;
        return message;
    },
};
function createBaseQueryChartResponse() {
    return { targetId: "", isValid: false, planetSurvey: undefined, systemSurveys: [] };
}
export const QueryChartResponse = {
    encode(message, writer = new BinaryWriter()) {
        if (message.targetId !== "") {
            writer.uint32(10).string(message.targetId);
        }
        if (message.isValid !== false) {
            writer.uint32(16).bool(message.isValid);
        }
        if (message.planetSurvey !== undefined) {
            PlanetarySurvey.encode(message.planetSurvey, writer.uint32(26).fork()).join();
        }
        for (const v of message.systemSurveys) {
            PlanetarySurvey.encode(v, writer.uint32(34).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const previousRecursionDepth = reader.__tsProtoDecodeDepth ?? 0;
        if (previousRecursionDepth >= 100) {
            throw new globalThis.Error("protobuf decode recursion limit exceeded");
        }
        reader.__tsProtoDecodeDepth = previousRecursionDepth + 1;
        try {
            const end = length === undefined ? reader.len : reader.pos + length;
            const message = createBaseQueryChartResponse();
            while (reader.pos < end) {
                const tag = reader.uint32();
                switch (tag >>> 3) {
                    case 1: {
                        if (tag !== 10) {
                            break;
                        }
                        message.targetId = reader.string();
                        continue;
                    }
                    case 2: {
                        if (tag !== 16) {
                            break;
                        }
                        message.isValid = reader.bool();
                        continue;
                    }
                    case 3: {
                        if (tag !== 26) {
                            break;
                        }
                        message.planetSurvey = PlanetarySurvey.decode(reader, reader.uint32());
                        continue;
                    }
                    case 4: {
                        if (tag !== 34) {
                            break;
                        }
                        message.systemSurveys.push(PlanetarySurvey.decode(reader, reader.uint32()));
                        continue;
                    }
                }
                if ((tag & 7) === 4 || tag === 0) {
                    break;
                }
                reader.skip(tag & 7);
            }
            return message;
        }
        finally {
            reader.__tsProtoDecodeDepth = previousRecursionDepth;
        }
    },
    fromJSON(object) {
        return {
            targetId: isSet(object.targetId)
                ? globalThis.String(object.targetId)
                : isSet(object.target_id)
                    ? globalThis.String(object.target_id)
                    : "",
            isValid: isSet(object.isValid)
                ? globalThis.Boolean(object.isValid)
                : isSet(object.is_valid)
                    ? globalThis.Boolean(object.is_valid)
                    : false,
            planetSurvey: isSet(object.planetSurvey)
                ? PlanetarySurvey.fromJSON(object.planetSurvey)
                : isSet(object.planet_survey)
                    ? PlanetarySurvey.fromJSON(object.planet_survey)
                    : undefined,
            systemSurveys: globalThis.Array.isArray(object?.systemSurveys)
                ? object.systemSurveys.map((e) => PlanetarySurvey.fromJSON(e))
                : globalThis.Array.isArray(object?.system_surveys)
                    ? object.system_surveys.map((e) => PlanetarySurvey.fromJSON(e))
                    : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.targetId !== "") {
            obj.targetId = message.targetId;
        }
        if (message.isValid !== false) {
            obj.isValid = message.isValid;
        }
        if (message.planetSurvey !== undefined) {
            obj.planetSurvey = PlanetarySurvey.toJSON(message.planetSurvey);
        }
        if (message.systemSurveys?.length) {
            obj.systemSurveys = message.systemSurveys.map((e) => PlanetarySurvey.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return QueryChartResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseQueryChartResponse();
        message.targetId = object.targetId ?? "";
        message.isValid = object.isValid ?? false;
        message.planetSurvey = (object.planetSurvey !== undefined && object.planetSurvey !== null)
            ? PlanetarySurvey.fromPartial(object.planetSurvey)
            : undefined;
        message.systemSurveys = object.systemSurveys?.map((e) => PlanetarySurvey.fromPartial(e)) || [];
        return message;
    },
};
function bytesFromBase64(b64) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
}
function base64FromBytes(arr) {
    return globalThis.Buffer.from(arr).toString("base64");
}
function isSet(value) {
    return value !== null && value !== undefined;
}
